# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sjinglong/桌面/LZ2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sjinglong/桌面/LZ2/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sjinglong/桌面/LZ2/build/CMakeFiles /home/sjinglong/桌面/LZ2/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sjinglong/桌面/LZ2/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lz

# Build rule for target.
lz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lz
.PHONY : lz

# fast build rule for target.
lz/fast:
	$(MAKE) -f CMakeFiles/lz.dir/build.make CMakeFiles/lz.dir/build
.PHONY : lz/fast

BitOperator/BitReader.o: BitOperator/BitReader.cc.o

.PHONY : BitOperator/BitReader.o

# target to build an object file
BitOperator/BitReader.cc.o:
	$(MAKE) -f CMakeFiles/lz.dir/build.make CMakeFiles/lz.dir/BitOperator/BitReader.cc.o
.PHONY : BitOperator/BitReader.cc.o

BitOperator/BitReader.i: BitOperator/BitReader.cc.i

.PHONY : BitOperator/BitReader.i

# target to preprocess a source file
BitOperator/BitReader.cc.i:
	$(MAKE) -f CMakeFiles/lz.dir/build.make CMakeFiles/lz.dir/BitOperator/BitReader.cc.i
.PHONY : BitOperator/BitReader.cc.i

BitOperator/BitReader.s: BitOperator/BitReader.cc.s

.PHONY : BitOperator/BitReader.s

# target to generate assembly for a file
BitOperator/BitReader.cc.s:
	$(MAKE) -f CMakeFiles/lz.dir/build.make CMakeFiles/lz.dir/BitOperator/BitReader.cc.s
.PHONY : BitOperator/BitReader.cc.s

BitOperator/BitWriter.o: BitOperator/BitWriter.cc.o

.PHONY : BitOperator/BitWriter.o

# target to build an object file
BitOperator/BitWriter.cc.o:
	$(MAKE) -f CMakeFiles/lz.dir/build.make CMakeFiles/lz.dir/BitOperator/BitWriter.cc.o
.PHONY : BitOperator/BitWriter.cc.o

BitOperator/BitWriter.i: BitOperator/BitWriter.cc.i

.PHONY : BitOperator/BitWriter.i

# target to preprocess a source file
BitOperator/BitWriter.cc.i:
	$(MAKE) -f CMakeFiles/lz.dir/build.make CMakeFiles/lz.dir/BitOperator/BitWriter.cc.i
.PHONY : BitOperator/BitWriter.cc.i

BitOperator/BitWriter.s: BitOperator/BitWriter.cc.s

.PHONY : BitOperator/BitWriter.s

# target to generate assembly for a file
BitOperator/BitWriter.cc.s:
	$(MAKE) -f CMakeFiles/lz.dir/build.make CMakeFiles/lz.dir/BitOperator/BitWriter.cc.s
.PHONY : BitOperator/BitWriter.cc.s

HuffmanCodec/HuffmanDecoder.o: HuffmanCodec/HuffmanDecoder.cc.o

.PHONY : HuffmanCodec/HuffmanDecoder.o

# target to build an object file
HuffmanCodec/HuffmanDecoder.cc.o:
	$(MAKE) -f CMakeFiles/lz.dir/build.make CMakeFiles/lz.dir/HuffmanCodec/HuffmanDecoder.cc.o
.PHONY : HuffmanCodec/HuffmanDecoder.cc.o

HuffmanCodec/HuffmanDecoder.i: HuffmanCodec/HuffmanDecoder.cc.i

.PHONY : HuffmanCodec/HuffmanDecoder.i

# target to preprocess a source file
HuffmanCodec/HuffmanDecoder.cc.i:
	$(MAKE) -f CMakeFiles/lz.dir/build.make CMakeFiles/lz.dir/HuffmanCodec/HuffmanDecoder.cc.i
.PHONY : HuffmanCodec/HuffmanDecoder.cc.i

HuffmanCodec/HuffmanDecoder.s: HuffmanCodec/HuffmanDecoder.cc.s

.PHONY : HuffmanCodec/HuffmanDecoder.s

# target to generate assembly for a file
HuffmanCodec/HuffmanDecoder.cc.s:
	$(MAKE) -f CMakeFiles/lz.dir/build.make CMakeFiles/lz.dir/HuffmanCodec/HuffmanDecoder.cc.s
.PHONY : HuffmanCodec/HuffmanDecoder.cc.s

HuffmanCodec/HuffmanEncoder.o: HuffmanCodec/HuffmanEncoder.cc.o

.PHONY : HuffmanCodec/HuffmanEncoder.o

# target to build an object file
HuffmanCodec/HuffmanEncoder.cc.o:
	$(MAKE) -f CMakeFiles/lz.dir/build.make CMakeFiles/lz.dir/HuffmanCodec/HuffmanEncoder.cc.o
.PHONY : HuffmanCodec/HuffmanEncoder.cc.o

HuffmanCodec/HuffmanEncoder.i: HuffmanCodec/HuffmanEncoder.cc.i

.PHONY : HuffmanCodec/HuffmanEncoder.i

# target to preprocess a source file
HuffmanCodec/HuffmanEncoder.cc.i:
	$(MAKE) -f CMakeFiles/lz.dir/build.make CMakeFiles/lz.dir/HuffmanCodec/HuffmanEncoder.cc.i
.PHONY : HuffmanCodec/HuffmanEncoder.cc.i

HuffmanCodec/HuffmanEncoder.s: HuffmanCodec/HuffmanEncoder.cc.s

.PHONY : HuffmanCodec/HuffmanEncoder.s

# target to generate assembly for a file
HuffmanCodec/HuffmanEncoder.cc.s:
	$(MAKE) -f CMakeFiles/lz.dir/build.make CMakeFiles/lz.dir/HuffmanCodec/HuffmanEncoder.cc.s
.PHONY : HuffmanCodec/HuffmanEncoder.cc.s

main.o: main.cc.o

.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/lz.dir/build.make CMakeFiles/lz.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i

.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/lz.dir/build.make CMakeFiles/lz.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s

.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/lz.dir/build.make CMakeFiles/lz.dir/main.cc.s
.PHONY : main.cc.s

tools/utilities.o: tools/utilities.cc.o

.PHONY : tools/utilities.o

# target to build an object file
tools/utilities.cc.o:
	$(MAKE) -f CMakeFiles/lz.dir/build.make CMakeFiles/lz.dir/tools/utilities.cc.o
.PHONY : tools/utilities.cc.o

tools/utilities.i: tools/utilities.cc.i

.PHONY : tools/utilities.i

# target to preprocess a source file
tools/utilities.cc.i:
	$(MAKE) -f CMakeFiles/lz.dir/build.make CMakeFiles/lz.dir/tools/utilities.cc.i
.PHONY : tools/utilities.cc.i

tools/utilities.s: tools/utilities.cc.s

.PHONY : tools/utilities.s

# target to generate assembly for a file
tools/utilities.cc.s:
	$(MAKE) -f CMakeFiles/lz.dir/build.make CMakeFiles/lz.dir/tools/utilities.cc.s
.PHONY : tools/utilities.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... lz"
	@echo "... BitOperator/BitReader.o"
	@echo "... BitOperator/BitReader.i"
	@echo "... BitOperator/BitReader.s"
	@echo "... BitOperator/BitWriter.o"
	@echo "... BitOperator/BitWriter.i"
	@echo "... BitOperator/BitWriter.s"
	@echo "... HuffmanCodec/HuffmanDecoder.o"
	@echo "... HuffmanCodec/HuffmanDecoder.i"
	@echo "... HuffmanCodec/HuffmanDecoder.s"
	@echo "... HuffmanCodec/HuffmanEncoder.o"
	@echo "... HuffmanCodec/HuffmanEncoder.i"
	@echo "... HuffmanCodec/HuffmanEncoder.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tools/utilities.o"
	@echo "... tools/utilities.i"
	@echo "... tools/utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

